### ISSUE TITLE
Error when converting to VTK

### ISSUE THREAD

**Issue by ghost** [jrwaine/LBM-CERNN#1]
The number of zeros in 

lbmReport.cpp
```
66    else
67        n_zeros = 6;
```

must be equal to in
fileTreat.py
`142    listFilenameStep = [i for i in listFilenameFlat if (("%05d" % step)+".bin") in i]`

in this case 5<>6.
As side note, vtk files do not add extra zeros to fix it:
exampleVTK.py
```
13    saveVTK3D(macr, info['ID'] + "macr" + str(step).zfill(6), points=True,normVal=1)
```

**Comment by jrwaine** [comment]
I updated the [fileTreat.py](https://github.com/jrwaine/LBM-CERNN/blob/ec07866fc1db7fed56cf2cb64c0b72e5858cab37/src/Post%20Processing/fileTreat.py) to specify the number of zeros as the same in [lbmReport.cpp](https://github.com/jrwaine/LBM-CERNN/blob/ec07866fc1db7fed56cf2cb64c0b72e5858cab37/src/CUDA/lbmReport.cpp). Can you check if that fixed the problem?
